# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'iPath' do
  use_frameworks!
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'

end
